import { Button } from "@/components/ui/button";
import { UploadPdf } from "@/components/uploadPdf";
export function Comparison() {
  return (
    <>
      <div className="px-4 py-6 md:py-12 lg:py-16">
        <div className="container prose max-w-none text-center">
          <div className="space-y-6">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
              Do LLMs dream about Synthetic Sheep?
            </h1>
          </div>
        </div>
      </div>
      <div className="flex justify-center mb-10">
        <UploadPdf />
      </div>
      <div className="bg-gray-50 border border-gray-200 dark:bg-gray-950 dark:border-gray-800">
        <div className="container grid gap-4 px-4 py-6 md:grid-cols-2 md:py-12 lg:gap-6 lg:px-6">
          <div className="p-4 rounded-lg bg-white shadow">
            <div className="space-y-4">
              <h2 className="text-2xl font-bold tracking-tighter">
                User-generated LLM Prompt
              </h2>
              <p className="text-xs text-gray-500 dark:text-gray-400">
                What was the original prompt provided by the user?
              </p>
            </div>
          </div>
          <div className="p-4 rounded-lg bg-white shadow">
            <div className="space-y-4">
              <h2 className="text-2xl font-bold tracking-tighter">
                Synthetically Augmented Prompt
              </h2>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                What is the evolved prompt generated by the AI?
              </p>
            </div>
          </div>
        </div>
        <div className="container grid gap-4 px-4 py-6 md:grid-cols-2 md:py-12 lg:gap-6 lg:px-6">
          <div className="p-4 rounded-lg bg-white shadow">
            <div className="space-y-4">
              <h2 className="text-2xl font-bold tracking-tighter">
                Semantic Similarity Score
              </h2>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                The semantic similarity score measures the closeness of the
                synthetic query to the user-generated prompt. A higher score
                indicates a better match in meaning and intent. This score helps
                evaluate the quality of the AI-generated response compared to
                the original user input.
              </p>
              <div className="grid gap-4">
                <div className="flex justify-between items-center">
                  <p className="text-sm">User-generated Response 1</p>
                  <span className="text-green-500 font-semibold">9.2</span>
                </div>
                <div className="flex justify-between items-center">
                  <p className="text-sm">User-generated Response 2</p>
                  <span className="text-green-500 font-semibold">8.7</span>
                </div>
                <div className="flex justify-between items-center">
                  <p className="text-sm">User-generated Response 3</p>
                  <span className="text-green-500 font-semibold">8.5</span>
                </div>
                <div className="flex justify-between items-center">
                  <p className="text-sm">User-generated Response 4</p>
                  <span className="text-green-500 font-semibold">8.3</span>
                </div>
                <div className="flex justify-between items-center">
                  <p className="text-sm">User-generated Response 5</p>
                  <span className="text-green-500 font-semibold">8.0</span>
                </div>
              </div>
            </div>
          </div>
          <div className="p-4 rounded-lg bg-white shadow">
            <div className="space-y-4">
              <h2 className="text-2xl font-bold tracking-tighter">
                Semantic Similarity Score
              </h2>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                The semantic similarity score measures the closeness of the
                synthetic query to the user-generated prompt. A higher score
                indicates a better match in meaning and intent. This score helps
                evaluate the quality of the AI-generated response compared to
                the original user input.
              </p>
              <div className="grid gap-4">
                <div className="flex justify-between items-center">
                  <p className="text-sm">Synthetic Response 1</p>
                  <span className="text-green-500 font-semibold">9.0</span>
                </div>
                <div className="flex justify-between items-center">
                  <p className="text-sm">Synthetic Response 2</p>
                  <span className="text-green-500 font-semibold">8.6</span>
                </div>
                <div className="flex justify-between items-center">
                  <p className="text-sm">Synthetic Response 3</p>
                  <span className="text-green-500 font-semibold">8.4</span>
                </div>
                <div className="flex justify-between items-center">
                  <p className="text-sm">Synthetic Response 4</p>
                  <span className="text-green-500 font-semibold">8.2</span>
                </div>
                <div className="flex justify-between items-center">
                  <p className="text-sm">Synthetic Response 5</p>
                  <span className="text-green-500 font-semibold">7.8</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
